-- liquibase formatted sql
-- changeset user:1724861079203-1
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name_str VARCHAR(255) NOT NULL,
    email_str VARCHAR(255) NOT NULL,
    user_name_str VARCHAR(255),
    password_byte BYTEA,
    ticket_byte BYTEA,
    user_status USER_STATUS NOT NULL,
    user_type USER_TYPE NOT NULL,
    access_mask JSON NOT NULL,
    settings JSON NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

-- changeset user:1724861079203-2
CREATE TABLE incident (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reporter_id BIGINT NOT NULL,
    operator_id BIGINT NOT NULL,
    incident_type INCIDENTTYPE,
    registration_dttm TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    exec_dttm TIMESTAMP WITH TIME ZONE NOT NULL,
    synchronization_dttm TIMESTAMP WITH TIME ZONE,
    location_type LOCATIONTYPE NOT NULL,
    incident_status INCIDENTSTATUS NOT NULL,
    description_text TEXT,
    filial_id BIGINT NOT NULL,
    address_json JSON NOT NULL,
    attributes_json JSON NOT NULL,
    CONSTRAINT incident_pkey PRIMARY KEY (id)
);

-- changeset user:1724861079203-3
CREATE TABLE filial (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    locations JSON NOT NULL,
    title_str VARCHAR(255) NOT NULL,
    description_txt TEXT,
    attributes_json JSON,
    CONSTRAINT filial_pkey PRIMARY KEY (id)
);

-- changeset user:1724861079203-4
CREATE TABLE reporter (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 11) NOT NULL,
    name_str VARCHAR(100),
    phone_str VARCHAR(100) NOT NULL,
    description_txt TEXT,
    attributes_json JSON,
    CONSTRAINT reporter_pkey PRIMARY KEY (id)
);

-- changeset user:1724861079203-5
ALTER TABLE incident
ADD CONSTRAINT incident_filial_id_fkey
FOREIGN KEY (filial_id) REFERENCES filial (id)
ON UPDATE NO ACTION
ON DELETE NO ACTION;

-- changeset user:1724861079203-6
ALTER TABLE incident
ADD CONSTRAINT incident_operator_id_fkey
FOREIGN KEY (operator_id) REFERENCES users (id)
ON UPDATE NO ACTION
ON DELETE NO ACTION;

-- changeset user:1724861079203-7
ALTER TABLE incident
ADD CONSTRAINT incident_reporter_id_fkey
FOREIGN KEY (reporter_id) REFERENCES reporter (id)
ON UPDATE NO ACTION
ON DELETE NO ACTION;